-- =====================================================
-- 默认数据源配置
-- =====================================================

-- 1. Kafka 数据源配置
INSERT INTO kafka_datasource_config (
    id,
    config_name,
    alert_type_id,
    brokers,
    topic_name,
    consumer_group,
    security_protocol,
    sasl_mechanism,
    username,
    password,
    session_timeout,
    max_poll_records,
    auto_offset_reset,
    data_format,
    field_mapping,
    description,
    is_enabled,
    connection_status,
    created_by,
    create_time,
    update_time
) VALUES
-- 网络攻击 Kafka 配置
(
    1,
    '网络攻击告警-Kafka数据源',
    1,
    'localhost:9092',
    'network-attack-alerts',
    'alert-system-network-group',
    'PLAINTEXT',
    NULL,
    NULL,
    NULL,
    30000,
    500,
    'latest',
    'json',
    NULL,
    '网络攻击告警的Kafka数据源配置',
    true,
    'unknown',
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- 恶意样本 Kafka 配置
(
    2,
    '恶意样本告警-Kafka数据源',
    2,
    'localhost:9092',
    'malicious-sample-alerts',
    'alert-system-malware-group',
    'PLAINTEXT',
    NULL,
    NULL,
    NULL,
    30000,
    500,
    'latest',
    'json',
    NULL,
    '恶意样本告警的Kafka数据源配置',
    true,
    'unknown',
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- 主机行为 Kafka 配置
(
    3,
    '主机行为告警-Kafka数据源',
    3,
    'localhost:9092',
    'host-behavior-alerts',
    'alert-system-host-group',
    'PLAINTEXT',
    NULL,
    NULL,
    NULL,
    30000,
    500,
    'latest',
    'json',
    NULL,
    '主机行为告警的Kafka数据源配置',
    true,
    'unknown',
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- 2. REST/HTTP 数据源配置
INSERT INTO rest_http_datasource_config (
    id,
    config_name,
    alert_type_id,
    endpoint_path,
    method,
    auth_type,
    basic_username,
    basic_password,
    bearer_token,
    api_key_name,
    api_key_value,
    content_type,
    custom_headers,
    rate_limit_enabled,
    rate_limit_requests,
    rate_limit_window,
    data_validation,
    field_mapping,
    description,
    is_enabled,
    created_by,
    create_time,
    update_time
) VALUES
-- 网络攻击 REST API 配置
(
    1,
    '网络攻击告警-REST API数据源',
    1,
    '/api/v1/alerts/network',
    'POST',
    'none',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'application/json',
    NULL,
    false,
    100,
    60,
    NULL,
    NULL,
    '网络攻击告警的REST API数据源配置',
    false,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- 恶意样本 REST API 配置
(
    2,
    '恶意样本告警-REST API数据源',
    2,
    '/api/v1/alerts/malware',
    'POST',
    'none',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'application/json',
    NULL,
    false,
    100,
    60,
    NULL,
    NULL,
    '恶意样本告警的REST API数据源配置',
    false,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- 主机行为 REST API 配置
(
    3,
    '主机行为告警-REST API数据源',
    3,
    '/api/v1/alerts/host',
    'POST',
    'none',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'application/json',
    NULL,
    false,
    100,
    60,
    NULL,
    NULL,
    '主机行为告警的REST API数据源配置',
    false,
    'system',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);